#### Tensors

Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized:

x = torch.empty(5, 3)
print(x)

tensor([[-1.5114e+29,  4.5698e-41, -1.5114e+29],
        [ 4.5698e-41,  1.8916e+23,  1.9433e-19],
        [ 7.0062e+22,  2.0283e-19,  1.1574e-32],
        [ 1.3563e-19,  4.4647e+30,  8.9036e-15],
        [ 1.1578e+27,  3.2498e+33,  4.6165e+24]])


In [3]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.0314, 0.1798, 0.4875],
        [0.8224, 0.8028, 0.1409],
        [0.1969, 0.7391, 0.8483],
        [0.6460, 0.2270, 0.8295],
        [0.4858, 0.5964, 0.0098]])


In [4]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
# Or create a tensor based on an existing tensor. These methods will
# reuse properties of the input tensor, eg. dtype, unless new values are provided by user.

x = x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes.
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtype and result has the same result.
print(x)

# Get the size
print(x.size()) # torch.Size is a tuple.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1553, -0.3454, -0.4532],
        [ 0.0665, -0.7901,  0.2190],
        [-0.6393,  0.9482, -0.1924],
        [-0.4384, -0.1794, -0.3500],
        [ 0.6896,  1.5440,  0.0877]])
torch.Size([5, 3])


#### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [8]:
# Addition: syntax 1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6437,  0.0033, -0.3716],
        [ 0.5120, -0.2259,  0.9058],
        [ 0.3466,  1.0011,  0.0132],
        [-0.1179,  0.7560,  0.1455],
        [ 1.2321,  1.8976,  0.4360]])


In [9]:
# Addition: syntax 2
print(torch.add(x, y))

tensor([[ 0.6437,  0.0033, -0.3716],
        [ 0.5120, -0.2259,  0.9058],
        [ 0.3466,  1.0011,  0.0132],
        [-0.1179,  0.7560,  0.1455],
        [ 1.2321,  1.8976,  0.4360]])


In [10]:
# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6437,  0.0033, -0.3716],
        [ 0.5120, -0.2259,  0.9058],
        [ 0.3466,  1.0011,  0.0132],
        [-0.1179,  0.7560,  0.1455],
        [ 1.2321,  1.8976,  0.4360]])


In [11]:
# Addition: in-place
# Note: Any operation that mutates a tensor in-place is
# post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
y.add_(x)
print(y)

tensor([[ 0.6437,  0.0033, -0.3716],
        [ 0.5120, -0.2259,  0.9058],
        [ 0.3466,  1.0011,  0.0132],
        [-0.1179,  0.7560,  0.1455],
        [ 1.2321,  1.8976,  0.4360]])


In [12]:
# You can use the standard NumPy-like indexing with all bells and whistles!
print(x[:, 1])

tensor([-0.3454, -0.7901,  0.9482, -0.1794,  1.5440])


In [13]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# If you have a one element tensor, use .item() to get the value as a Python number.
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.0610])
-2.0609524250030518


#### NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations(if the Torch Tensor is on CPU), and changing one will change the other.

In [16]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

# All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [18]:
# Let us run this cell only if CUDA is available
# We will use 'torch.device' object to move tensors in and out of GPU.

if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

tensor([-1.0610], device='cuda:0')
tensor([-1.0610], dtype=torch.float64)
